Fixed a typo in stop.py which caused a different exception to be raised than was desired
